- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_package_name }}"
    state: present

- name: Install Docker Compose
  ansible.builtin.pip:
    name: docker-compose
    version: "{{ docker_compose_version }}"
    state: present
